name: mobile
description: An app for on-demand health services.
version: 2023.04.17+507

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  url_launcher: ^6.0.10
  flutter_secure_storage: ^9.0.0
  provider: ^6.0.3
  http: ^1.1.0
  local_auth: ^2.1.2
  flutter_week_view: ^1.2.0
  intl: ^0.18.1
  dotted_border: ^2.0.0+1
  lazy_data_table: ^0.3.1
  lazy_data_table_plus: ^1.0.0
  simple_tooltip: ^1.0.0
  simple_star_rating: ^0.0.3
  syncfusion_flutter_calendar: ^23.1.39
  toggle_switch: ^2.0.1
  geolocator: ^10.1.0
  validators: ^3.0.0
  google_maps_flutter: ^2.0.11
  firebase_core: ^2.17.0
  firebase_auth: ^4.10.1
  firebase_messaging: ^14.6.9
  image_picker: ^1.0.4
  share: ^2.0.4
  visibility_aware_state: ^1.0.3
  google_sign_in: ^6.1.5
  sign_in_with_apple: ^4.0.0
  crypto: ^3.0.0
  keyboard_actions: ^4.0.1
  mailer: ^6.0.1
  shared_preferences: ^2.0.12
  firebase_analytics: ^10.5.1
  overlay_support: ^2.0.1
  event: ^2.1.2
  eventsubscriber: ^2.1.3
  logger: ^2.0.2+1
  maps_launcher: ^2.0.1
  flutter_cupertino_datetime_picker: ^3.0.0
  firebase_dynamic_links: ^5.3.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  country_code_picker: ^3.0.0
  internet_connection_checker: ^1.0.0+1
  app_settings: ^5.1.1
  permission_handler: ^11.0.1
  fluttertoast: ^8.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/onboarding/
    - assets/ca/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Thin.ttf
        - asset: assets/fonts/Inter-ExtraLight.ttf
        - asset: assets/fonts/Inter-Light.ttf
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
        - asset: assets/fonts/Inter-ExtraBold.ttf
        - asset: assets/fonts/Inter-Black.ttf
    - family: Jost
      fonts:
        - asset: assets/fonts/jost/Jost-Thin.ttf
        - asset: assets/fonts/jost/Jost-ExtraLight.ttf
        - asset: assets/fonts/jost/Jost-Light.ttf
        - asset: assets/fonts/jost/Jost-Regular.ttf
        - asset: assets/fonts/jost/Jost-Medium.ttf
        - asset: assets/fonts/jost/Jost-SemiBold.ttf
        - asset: assets/fonts/jost/Jost-ExtraBold.ttf
        - asset: assets/fonts/jost/Jost-Black.ttf
